package avps.labs.client.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2017-11-29T02:13:24.337+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "CurrencyWSService", 
                  wsdlLocation = "http://127.0.0.1:8080/AVPS_lab7/CurrencyWSServlet?wsdl",
                  targetNamespace = "http://labs.avps/") 
public class CurrencyWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://labs.avps/", "CurrencyWSService");
    public final static QName CurrencyWSPort = new QName("http://labs.avps/", "CurrencyWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/AVPS_lab7/CurrencyWSServlet?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CurrencyWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/AVPS_lab7/CurrencyWSServlet?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CurrencyWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CurrencyWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurrencyWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CurrencyWS
     */
    @WebEndpoint(name = "CurrencyWSPort")
    public CurrencyWS getCurrencyWSPort() {
        return super.getPort(CurrencyWSPort, CurrencyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyWS
     */
    @WebEndpoint(name = "CurrencyWSPort")
    public CurrencyWS getCurrencyWSPort(WebServiceFeature... features) {
        return super.getPort(CurrencyWSPort, CurrencyWS.class, features);
    }

}
