package avps.labs.client.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2017-11-29T02:13:24.265+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://labs.avps/", name = "CurrencyWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CurrencyWS {

    @WebMethod
    @RequestWrapper(localName = "getCurrencies", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetCurrencies")
    @ResponseWrapper(localName = "getCurrenciesResponse", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetCurrenciesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getCurrencies();

    @WebMethod
    @RequestWrapper(localName = "getCurrencyInfo", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetCurrencyInfo")
    @ResponseWrapper(localName = "getCurrencyInfoResponse", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetCurrencyInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public avps.labs.client.stubs.Currency getCurrencyInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getConvertedSum", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetConvertedSum")
    @ResponseWrapper(localName = "getConvertedSumResponse", targetNamespace = "http://labs.avps/", className = "avps.labs.client.stubs.GetConvertedSumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Float getConvertedSum(
        @WebParam(name = "arg0", targetNamespace = "")
        avps.labs.client.stubs.Currency arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2
    );
}
